version: 2.1

orbs:
  node: circleci/node@7.0.0

jobs:
  build-service:
    docker:
      - image: eclipse-temurin:25-alpine

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache sbt

      - run:
          name: Compile tests
          command: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.sbt
            - ~/.ivy2
            - ~/.cache/coursier
          key: v1-dependencies-{{ checksum "build.sbt" }}

      - run:
          name: Build and Package Service
          command: sbt "project service" clean update test assembly package

  build-front-end:
    executor:
      name: node/default
      tag: 24.0.0
    working_directory: ~/repo/image-train-filters-fe
    steps:
      - checkout:
          path: ~/repo
      - node/install-packages:
          pkg-manager: yarn

workflows:
  build_and_test:
    jobs:
      - build-service
      - build-front-end