version: 2
jobs:
  build-service:
    docker:
      - image: eclipse-temurin:21-alpine

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: sbt "project service" clean update test assembly package

  build-front-end:
    docker:
        - image: cimg/node:20.0.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: yarn install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-service
      - build-front-end