name: E2E e2e-image-train-filters

on: push

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: sbt/setup-sbt@v1
      - name: Build and test
        shell: bash
        run: sbt -v +test

      - name: Start Docker
        run: make dcup-full-action

      - name: Docker Compose Up Fail!
        if: failure()
        run: |
          make docker-logs

      - name: Run Cypress
        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: sbt/setup-sbt@v1
      - name: Build and test
        shell: bash
        run: sbt -v +test

      - name: Start Docker
        run: make dcup-full-action

      - name: Docker Compose Up Fail!
        if: failure()
        run: |
          make docker-logs

      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: sbt/setup-sbt@v1
      - name: Build and test
        shell: bash
        run: sbt -v +test

      - name: Start Docker
        run: make dcup-full-action

      - name: Docker Compose Up Fail!
        if: failure()
        run: |
          make docker-logs

      - name: Run Cypress
        run: make cypress-firefox

  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - uses: sbt/setup-sbt@v1
      - name: Build and test
        shell: bash
        run: sbt -v +test

      - name: Start Docker
        run: make dcup-full-action

      - name: Docker Compose Up Fail!
        if: failure()
        run: |
          make docker-logs

      - name: Run Cypress
        run: make cypress-edge
