name: Build image-train-filters-web

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'Readme.md'
  pull_request_target:
    types:
      - closed
    paths-ignore:
      - 'README.md'
      - 'Readme.md'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'adopt'
    - uses: actions/setup-node@v5
      with:
        node-version: 22

    - uses: sbt/setup-sbt@v1
    - name: Build and test
      shell: bash
      run: sbt -v +test

    - name: Install Jest Image Train Filters Web
      run: cd image-train-filters-fe && yarn && yarn add jest --dev

    - name: Node Coverage
      run: cd image-train-filters-fe && npm run coverage

    - name: Run tests
      run: make build

    - name: Run Build and Coverage
      run: make coverage
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Make assembly
      run: sbt assembly
